# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operator_seller_login.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(441, 777)
        self.gridLayout_2 = QtWidgets.QGridLayout(login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(login)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 699))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_push_button = QtWidgets.QPushButton(self.layoutWidget)
        self.login_push_button.setObjectName("login_push_button")
        self.horizontalLayout.addWidget(self.login_push_button)
        self.register_push_button = QtWidgets.QPushButton(self.layoutWidget)
        self.register_push_button.setObjectName("register_push_button")
        self.horizontalLayout.addWidget(self.register_push_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.login_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_password.setObjectName("login_password")
        self.gridLayout_3.addWidget(self.login_password, 1, 1, 1, 1)
        self.login_email = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_email.setObjectName("login_email")
        self.gridLayout_3.addWidget(self.login_email, 0, 1, 1, 1)
        self.login_email_label = QtWidgets.QLabel(self.layoutWidget)
        self.login_email_label.setObjectName("login_email_label")
        self.gridLayout_3.addWidget(self.login_email_label, 0, 0, 1, 1)
        self.login_pass_label = QtWidgets.QLabel(self.layoutWidget)
        self.login_pass_label.setObjectName("login_pass_label")
        self.gridLayout_3.addWidget(self.login_pass_label, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_label = QtWidgets.QLabel(self.layoutWidget)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 401, 699))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.login_password_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.login_password_2.setObjectName("login_password_2")
        self.gridLayout_5.addWidget(self.login_password_2, 1, 1, 1, 1)
        self.login_email_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.login_email_2.setObjectName("login_email_2")
        self.gridLayout_5.addWidget(self.login_email_2, 0, 1, 1, 1)
        self.login_email_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.login_email_label_2.setObjectName("login_email_label_2")
        self.gridLayout_5.addWidget(self.login_email_label_2, 0, 0, 1, 1)
        self.login_pass_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.login_pass_label_2.setObjectName("login_pass_label_2")
        self.gridLayout_5.addWidget(self.login_pass_label_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.status_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.status_label_2.setObjectName("status_label_2")
        self.verticalLayout_2.addWidget(self.status_label_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_push_button_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.login_push_button_2.setObjectName("login_push_button_2")
        self.horizontalLayout_2.addWidget(self.login_push_button_2)
        self.register_push_button_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.register_push_button_2.setObjectName("register_push_button_2")
        self.horizontalLayout_2.addWidget(self.register_push_button_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(login)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.login_push_button.setText(_translate("login", "login"))
        self.register_push_button.setText(_translate("login", "register"))
        self.login_email_label.setText(_translate("login", "email"))
        self.login_pass_label.setText(_translate("login", "password"))
        self.status_label.setText(_translate("login", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("login", "seller"))
        self.login_email_label_2.setText(_translate("login", "email"))
        self.login_pass_label_2.setText(_translate("login", "password"))
        self.status_label_2.setText(_translate("login", "TextLabel"))
        self.login_push_button_2.setText(_translate("login", "login"))
        self.register_push_button_2.setText(_translate("login", "register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("login", "operator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QWidget()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())

