# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\operator_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(507, 121)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.Logout_button = QtWidgets.QPushButton(Form)
        self.Logout_button.setObjectName("Logout_button")
        self.gridLayout.addWidget(self.Logout_button, 1, 0, 1, 2)
        self.email = QtWidgets.QLabel(Form)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Logout_button.setText(_translate("Form", "Logout"))
        self.email.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
